require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

def default_pods
  # Required by RNFirebase
  # pod 'Firebase/Core', '~> 6.13.0'
  # pod 'Firebase/Auth', '~> 6.13.0'
  # pod 'Firebase/Messaging', '~> 6.13.0'
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  # pod 'RNFirebase/Crashlytics', :path => '../node_modules/react-native-firebase/ios'

  # Pods for PodTest Scrashlytics
  # pod 'Fabric', '~> 1.10.2'
  # pod 'Crashlytics', '~> 3.14.0'
  # pod 'GoogleIDFASupport', '~> 3.14.0'

  # (Recommended) Pod for Google Analytics
  # pod 'Firebase/Analytics'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"


  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'development' do
  default_pods
end

target 'staging' do
  default_pods
end

target 'production' do
  default_pods
end
